### ISSUE TITLE
Query Parameters not used in Signature

### ISSUE THREAD

**Issue by aadlung** [jenwachter/Paw-AkamaiOpenEdgeGridAuthorization#2]
Hi,
I checked the PAPI features, and it seems the signature does not honor the query string (url parameters), so I added the following after line 81:

`
if(parts.query !== "") {
    value = request.method + '\thttps\t' + parts.host + '\t' + parts.path + '?' + parts.query + '\t\t';
  }
`

Regards,
Andy

**Comment by jenwachter** [comment]
fixed in https://github.com/jenwachter/Paw-AkamaiOpenEdgeGridAuthorization/pull/3
